name: CI Pipeline for testing & build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

permissions:
  issues: write
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true   

jobs:
  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Create test-results directory
        run: mkdir -p test-results

      - name: Run tests
        run: npm test -- --reporter junit --reporter-options "mochaFile=test-results/results-${{ matrix.node }}.xml"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node }}
          path: test-results/

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: AbdulAhad390
          minimum-approvals: 1
          issue-title: "Approval needed for build on ${{ github.ref }}"
          issue-body: "Please approve or deny the build for commit ${{ github.sha }}."
          secret: ${{ secrets.GITHUB_TOKEN }}   

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Store build output
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          
